tasks:
  - name: Setup Ollama
    before: |
      # Create a local bin folder for Ollama
      mkdir -p $HOME/bin
      curl -L https://ollama.com/download/ollama-linux-amd64 -o $HOME/bin/ollama
      chmod +x $HOME/bin/ollama

      # Persist models in the workspace
      mkdir -p /workspace/.ollama

      # Add Ollama to PATH and set OLLAMA_MODELS for all future shells
      gp env PATH="$HOME/bin:$PATH"
      gp env OLLAMA_MODELS="/workspace/.ollama"
    init: |
      # Pull the llama3 model
      ollama pull llama3
    command: |
      ollama serve > /tmp/ollama.log 2>&1 &

ports:
  - port: 11434
    onOpen: ignore
    visibility: public
